# Generated by Django 3.1.7 on 2021-09-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackapp', '0002_auto_20210915_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_photo',
            field=models.ImageField(default='default.jpg', upload_to='courses/'),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(default='Fundamental Course', max_length=200),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='lecturer_profile',
            field=models.ImageField(default='default.jpg', upload_to='lecturers/'),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='lecturer_skill',
            field=models.CharField(default='Master degree', max_length=200),
        ),
    ]
