# Generated by Django 3.1.7 on 2021-09-20 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackapp', '0003_auto_20210919_2025'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolAdmin',
        ),
    ]
