# Generated by Django 3.1.7 on 2021-09-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackapp', '0004_delete_schooladmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_photo',
            field=models.ImageField(default='static/default.jpg', upload_to='static/courses/'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='lecturer_profile',
            field=models.ImageField(default='static/default.jpg', upload_to='static/lecturers/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile',
            field=models.ImageField(default='static/default.jpg', upload_to='static/images/'),
        ),
    ]
