# Generated by Django 3.1.7 on 2021-09-23 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackapp', '0006_auto_20210923_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_photo',
            field=models.ImageField(default='default.jpg', upload_to='courses/'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='lecturer_profile',
            field=models.ImageField(default='default.jpg', upload_to='lecturers/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
