# Generated by Django 3.1.7 on 2021-09-15 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='academic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbackapp.academic'),
        ),
    ]
